In [4]:
import cv2
import numpy as np

fileName = list(range(78))

img = cv2.imread('0011.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.bilateralFilter(gray, 11, 17, 17)

kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(gray,kernel,iterations = 2)
kernel = np.ones((4,4),np.uint8)
dilation = cv2.dilate(erosion,kernel,iterations = 2)

edged = cv2.Canny(dilation, 30, 50)

_, contours, hierarchy = cv2.findContours(edged, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

rects = [cv2.boundingRect(cnt) for cnt in contours]
rects = sorted(rects,key=lambda  x:x[1],reverse=True)
print(rects)

i = -1
j = 1
y_old = 5000
x_old = 5000
for rect in rects:
    x,y,w,h = rect
    area = w * h

    if area > 8000 and area < 1200000:

        if (y_old - y) > 200:
            i += 1
            y_old = y

        if abs(x_old - x) > 300:
            x_old = x
            x,y,w,h = rect

            out = img[y+10:y+h-10,x+10:x+w-10]
            cv2.imwrite('cropped\\' + str(fileName[i]) + '_' + str(j) + '.jpg', out)

            j+=1

[(1645, 3357, 9, 10), (1645, 3357, 9, 10), (1246, 3355, 9, 11), (1246, 3355, 9, 11), (637, 3306, 9, 9), (637, 3306, 9, 9), (1732, 3305, 9, 13), (1732, 3305, 9, 13), (1499, 3305, 9, 11), (1499, 3305, 9, 11), (1371, 3304, 9, 12), (1371, 3304, 9, 12), (868, 3304, 10, 11), (868, 3304, 10, 11), (556, 3303, 10, 11), (556, 3303, 10, 11), (1064, 3256, 9, 9), (1064, 3256, 9, 9), (1006, 3255, 9, 10), (1006, 3255, 9, 10), (1002, 3100, 9, 11), (1002, 3100, 9, 11), (1047, 3097, 20, 17), (1078, 3092, 15, 19), (1078, 3092, 15, 19), (1635, 3087, 42, 56), (1635, 3087, 42, 56), (1936, 3074, 46, 56), (1936, 3074, 46, 56), (1075, 3074, 10, 10), (1075, 3074, 10, 10), (753, 3068, 55, 62), (753, 3068, 55, 62), (1047, 3066, 53, 67), (1055, 3066, 45, 67), (1345, 3065, 49, 65), (1345, 3065, 49, 65), (442, 3059, 57, 87), (442, 3059, 57, 87), (1909, 3045, 115, 117), (1909, 3045, 115, 117), (1612, 3045, 117, 116), (1612, 3045, 117, 116), (1316, 3044, 115, 117), (1316, 3044, 115, 117), (1022, 3044, 115, 117), (1022

In [20]:
img = cv2.imread("001.jpg",)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

binary = cv2.bitwise_not(gray)

(_,contours,_) = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
#print(contours)
for contour in contours:
    (x,y,w,h) = cv2.boundingRect(contour)
    rect = cv2.minAreaRect(contour)
    box = cv2.boxPoints(rect)
    #print(box)
    if w<125 and w>115 and h<125 and h>115:
        out = img[y+10:y+h-10,x+10:x+w-10]
        cv2.imwrite('cropped\\' + str(x) + '_' + str(y) + '.jpg', out)


[[2288. 3439.]
 [2288. 3432.]
 [2295. 3432.]
 [2295. 3439.]]
[[1855. 3407.]
 [1855. 3407.]
 [1855. 3407.]
 [1855. 3407.]]
[[1855. 3400.]
 [1855. 3400.]
 [1855. 3400.]
 [1855. 3400.]]
[[1848. 3407.]
 [1848. 3400.]
 [1855. 3400.]
 [1855. 3407.]]
[[2535. 3391.]
 [2528. 3391.]
 [2528. 3384.]
 [2535. 3384.]]
[[1606. 3383.]
 [1606. 3383.]
 [1606. 3383.]
 [1606. 3383.]]
[[1240. 3383.]
 [1240. 3383.]
 [1240. 3383.]
 [1240. 3383.]]
[[1075. 3383.]
 [1075. 3383.]
 [1076. 3383.]
 [1076. 3383.]]
[[1000. 3383.]
 [1000. 3383.]
 [1000. 3383.]
 [1000. 3383.]]
[[ 968. 3383.]
 [ 968. 3383.]
 [ 968. 3383.]
 [ 968. 3383.]]
[[1317.4    3383.8003]
 [1317.0001 3383.0005]
 [1319.0001 3382.0005]
 [1319.4    3382.8003]]
[[1097.6    3383.8003]
 [1095.6    3382.8003]
 [1095.9999 3382.0005]
 [1097.9999 3383.0005]]
[[1592. 3381.]
 [1592. 3381.]
 [1592. 3381.]
 [1592. 3381.]]
[[1072.0002 3383.0005]
 [1071.5002 3382.5005]
 [1074.0002 3380.0005]
 [1074.5002 3380.5005]]
[[1072. 3379.]
 [1072. 3379.]
 [1072. 3380.]
 [107

 [1312. 1983.]]
[[1126. 1983.]
 [1126. 1983.]
 [1127. 1983.]
 [1127. 1983.]]
[[1111. 1983.]
 [1111. 1983.]
 [1111. 1983.]
 [1111. 1983.]]
[[1088. 1983.]
 [1088. 1983.]
 [1088. 1983.]
 [1088. 1983.]]
[[1083. 1983.]
 [1083. 1983.]
 [1083. 1983.]
 [1083. 1983.]]
[[1427.1998 1983.3999]
 [1426.9999 1983.    ]
 [1429.7999 1981.6001]
 [1429.9999 1982.    ]]
[[1038. 1983.]
 [1038. 1982.]
 [1040. 1982.]
 [1040. 1983.]]
[[1335. 1981.]
 [1335. 1981.]
 [1335. 1981.]
 [1335. 1981.]]
[[1085.6001 1983.2002]
 [1084.6001 1981.2002]
 [1085.     1981.0002]
 [1086.     1983.0002]]
[[1078.     1983.0001]
 [1077.5    1981.5001]
 [1082.6001 1979.8002]
 [1083.1001 1981.3002]]
[[1431. 1980.]
 [1431. 1980.]
 [1431. 1980.]
 [1431. 1980.]]
[[1231. 1980.]
 [1231. 1980.]
 [1231. 1980.]
 [1231. 1980.]]
[[1076.5001 1981.5002]
 [1076.0001 1981.0002]
 [1077.0001 1980.0002]
 [1077.5001 1980.5002]]
[[1328. 1979.]
 [1328. 1979.]
 [1328. 1979.]
 [1328. 1979.]]
[[1216. 1971.]
 [1216. 1971.]
 [1216. 1971.]
 [1216. 1971.]]
[[

 [551. 693.]]
[[548. 691.]
 [548. 691.]
 [548. 692.]
 [548. 692.]]
[[550. 690.]
 [550. 690.]
 [551. 690.]
 [551. 690.]]
[[2102.  688.]
 [2102.  688.]
 [2103.  689.]
 [2103.  689.]]
[[2103.  695.]
 [2096.  695.]
 [2096.  688.]
 [2103.  688.]]
[[1224.  695.]
 [1224.  688.]
 [1231.  688.]
 [1231.  695.]]
[[2256.  695.]
 [2256.  680.]
 [2263.  680.]
 [2263.  695.]]
[[2127.  679.]
 [2126.  679.]
 [2126.  677.]
 [2127.  677.]]
[[1218.  678.]
 [1217.  678.]
 [1217.  676.]
 [1218.  676.]]
[[1896.  675.]
 [1896.  675.]
 [1896.  676.]
 [1896.  676.]]
[[1143.  673.]
 [1143.  673.]
 [1143.  673.]
 [1143.  673.]]
[[2112.  675.]
 [2112.  672.]
 [2113.  672.]
 [2113.  675.]]
[[2023.  672.]
 [2023.  672.]
 [2023.  674.]
 [2023.  674.]]
[[1896.       798.99994]
 [1896.       671.99994]
 [2023.       671.99994]
 [2023.       798.99994]]
[[1899.  672.]
 [1899.  672.]
 [1900.  672.]
 [1900.  672.]]
[[1898.0002  675.0001]
 [1895.5002  672.5001]
 [1896.0002  672.0001]
 [1898.5002  674.5001]]
[[1727.  672.]
